In [2]:
#1)Display “Hello World” in your output screen.
print("hello world")

hello world


In [10]:
#2)Get the input from the user and perform addition of two numbers.
a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
c=a+b
print("the sum:",c)

Enter a number:5
Enter a number:10
the sum: 15


In [11]:
#3)swap two variables without temp variable
a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
print("A=",a)
print("B=",b)
print("After swapping:")
a,b=b,a
print("A=",a)
print("B=",b)

Enter a number:5
Enter a number:3
A= 5
B= 3
After swapping:
A= 3
B= 5


In [12]:
#4)convert the entered kilometres ( Convertion  Factor= 0.621371)
a=int(input("enter km value: "))
miles=a*0.621371
print("the miles value is :  ", miles)

enter km value: 1
the miles value is :   0.621371


In [13]:
#5)check whether the given number is positive, negative or 0
a=int(input("enter number 1 : "))
if a>=0:
    print("the number is positive")
else:
    print(" the number is negative")

enter number 1 : 6
the number is positive


In [14]:
#6)verify that the given year is a leap year
a=int(input("enter year : "))
if a%4==0:
    if a%100==0:
        if a%400==0:
            print("the year is a leap year")
        else:
            print("the year is not a leap year")
    else:
        print("the year is a leap year")
else:
    print("the year is not a leap year")

enter year : 2004
the year is a leap year


In [15]:
#7)display the prime numbers within the given interval
a=int(input("Enter a start range:"))
b=int(input("Enter a end range:"))
c=0
if a==1:
    a=2
for i in range (a,b):
    c=0
    for j in range (2,i):       
        if i%j==0:
            c=1
    if c==0:
        print(i)

Enter a start range:1
Enter a end range:10
2
3
5
7


In [16]:
#8)display the Fibonacci sequence up to n-th term
n = int(input("Enter the number of terms: "))
a = 0
b = 1
if n <= 0:
    print("Invalid input!")
elif n == 1:
    print("Fibonacci sequence up to", n, "term:")
    print(a)
else:
    print("Fibonacci sequence up to", n, "terms:")
    print(a)
    print(b)
    for i in range(2, n):
        c = a + b
        print(c)
        a = b
        b = c

Enter the number of terms: 10
Fibonacci sequence up to 10 terms:
0
1
1
2
3
5
8
13
21
34


In [9]:
#9) check if the number is an Armstrong number or not
n=int(input("enter a number : "))
num=n
elem=[]
while n>0 :
    a=n%10
    elem.append(a)
    n=n//10
elem1=elem[::-1]
sum=0
for i in elem:
    sum=sum+(i**3)
if sum==num:
    print("its an armstrong number")
else:
    print("its not an armstrong number")


enter a number : 153
its an armstrong number


In [19]:
#10) Find the Sum of natural numbers up to n-th term
n=int(input("enter the range : "))
sum=0
for i in range(n+1):
    sum=sum+i
print("the sum of  integers in range", n, "is : ",sum )

enter the range : 10
the sum of  integers in range 10 is :  55


In [21]:
#11)Write a function called show_stars(rows). If rows are 5, it should print the following:

n=int(input("enter the number of rows : "))
for i in range(n+1):
    print("*"*i)

enter the number of rows : 5

*
**
***
****
*****


In [23]:
#12)Write a program to remove characters from a string starting from zero up to n and return a new string.

str=input("enter a string: ")
n=int(input("enter the range from 0 : "))
print(str[n::])

enter a string: what is this ... ?
enter the range from 0 : 4
 is this ... ?


In [24]:
#13) Iterate the given list of numbers and print only those numbers which are divisible by 5

n=int(input("enter the range : "))
list=[]
for i in range (0,n):
    c=int(input("enter the elements : "))
    list.append(c)
print("the numbers divisibl by 5 are : ")
for i in list:
    if i%5==0:
        print(i)
    
    

enter the range : 5
enter the elements : 10
enter the elements : 2
enter the elements : 14
enter the elements : 15
enter the elements : 28
the numbers divisibl by 5 are : 
10
15


In [25]:
#14) Write a program to find how many times substring “Hi” appears in the given string.
g=input("enter a sentence : ")
list=g.split(' ')
n=len(list)
c=0
for i in range (n):
    if list[i]=='hi':
        c+=1
if c!=0:
    print("'hi' is present {} times".format(c))
else:
    print("'hi' is not present")
        

enter a sentence : hi this is vickey hi
'hi' is present 2 times


In [26]:
#15) Print the following pattern
n=int(input("enter the range : "))
for i in range (1,n+1):
    for j in range (0,i):
        print(i, end="")
    print(end="\n")

enter the range : 5
1
22
333
4444
55555


In [27]:
#16)Write a program to check if the given number is a palindrome number.
name=input("enter the number : ")
rev=name[::-1]
if name==rev:
    print("its a palindrome")
else :
    print("its not a palindrome")

enter the number : 545
its a palindrome


In [28]:
#17) Python program to interchange first and last elements in a list
n=int(input("enter the range : "))
list=[]
for i in range (0,n):
    c=int(input("enter the elements : "))
    list.append(c)
fir=min(list)
lst=max(list)
list[0]=lst
list[-1]=fir
print(list)

enter the range : 5
enter the elements : 1
enter the elements : 2
enter the elements : 3
enter the elements : 4
enter the elements : 5
[5, 2, 3, 4, 1]


In [29]:
#18)Python program to swap two elements in a list
n=int(input("enter the range : "))
list=[]
for i in range (0,n):
    c=int(input("enter the elements : "))
    list.append(c)
print(list)
f=int(input("enter the index 1: "))
s=int(input("enter the index 2: "))
t=list[f]
list[f]=list[s]
list[s]=t
print(list)

enter the range : 5
enter the elements : 1
enter the elements : 2
enter the elements : 3
enter the elements : 4
enter the elements : 5
[1, 2, 3, 4, 5]
enter the index 1: 1
enter the index 2: 3
[1, 4, 3, 2, 5]


In [31]:
#19)Python | Ways to find length of list

n=int(input("enter the range : "))
list=[]
for i in range (0,n):
    c=int(input("enter the elements : "))
    list.append(c)
l=len(list)
print("len operator : ", l)

enter the range : 5
enter the elements : 2
enter the elements : 3
enter the elements : 4
enter the elements : 5
enter the elements : 6
len operator :  5


In [32]:
#20)Maximum of two numbers in Python
#21)Minimum of two numbers in Python

n=int(input("enter the range : "))
list=[]
for i in range (0,n):
    c=int(input("enter the elements : "))
    list.append(c)
ma=max(list)
mi=min(list)
print("the maximum of the list is : ", ma)
print("the minimum of the list is : ", mi)

enter the range : 5
enter the elements : 3
enter the elements : 5
enter the elements : 1
enter the elements : 7
enter the elements : 4
the maximum of the list is :  7
the minimum of the list is :  1


In [30]:
#22)Python program to check whether the string is Symmetrical or Palindrome

name=input("enter the name : ")
rev=name[::-1]
if name==rev:
    print("its a palindrome")
else :
    print("its not a palindrome")

enter the name : malayalam
its a palindrome


In [33]:
#23)Reverse words in a given String in Python

name=input("enter the name : ")
rev=name[::-1]
print(rev)

enter the name : this is fun
nuf si siht


In [47]:
#24)Ways to remove i’th character from string in Python
name=input("enter the name : ")
i=int(input("enter pos u want to remove : "))
c=name[i]
name1=name.replace(c,'')
print(name1)

enter the name : cherry
enter pos u want to remove : 2
chrry


In [48]:
#25)Find length of a string in python 
a=input("enter  string : ")
num=len(a)
print(num)

enter  string : kokushibo
9


In [45]:
#26)Python program to print even length words in a string
a=input("enter  string : ")
even=a[1::2]
print(even)

enter  string : this is even
hsi vn


In [34]:
#27)Python program to Find the size of a Tuple

tup=(2,3,4,5,6,7)
n=len(tup)
print("the length of the tuple is : ", n)

the length of the tuple is :  6


In [35]:
#28)Python – Maximum and Minimum K elements in Tuple

tup=(2,3,4,5,6,7)
ma=max(tup)
mi=min(tup)
print("the maximum of the tuple is : ", ma)
print("the minimum of the tuple is : ", mi)

the maximum of the tuple is :  7
the minimum of the tuple is :  2


In [36]:
#29)Python – Sum of tuple elements

tup=(2,3,4,5,6,7)
sum=0
for i in tup:
    sum=sum+i
print("the sum of the tuple is : ", sum)

the sum of the tuple is :  27


In [24]:
#31. Create a list of tuples from given list having number and its cube in each tuple.
def cubeoflist(li):
    result=[(num, num**3) for num in li]
    return result
li = []
n=int(input("enter the RANGE : "))
for i in range(n):
    a=int(input("enter elements: "))
    li.append(a)
print(cubeoflist(li))

[(3, 27), (2, 8), (1, 1), (4, 64)]


In [36]:
#32.Python - Sort python dictionaries by key or value
myDict = {'ravi': 10, 'rajnish': 9,'sanjeev': 15, 'yash': 2, 'suraj': 32}
 
myKeys = list(myDict.keys())
myKeys.sort()
sorted_dict = {i: myDict[i] for i in myKeys}
 
print(sorted_dict)

{'rajnish': 9, 'ravi': 10, 'sanjeev': 15, 'suraj': 32, 'yash': 2}


In [3]:
#33. Python dictionary with keys having multiple values.
dic = {}

a,b,c= 5, 3, 10

p,q,r= 12, 6, 9
dic["x-y+z"] = [a-b+c,p-q+r]
print(dic)

{'x-y+z': [12, 15]}


In [4]:
#34. Python program to find the sum of all items in a dictionary.
dic={ 'x':455, 'y':223, 'z':300, 'p':908 }
print("Dictionary: ", dic)
print("sum: ",sum(dic.values()))

Dictionary:  {'x': 455, 'y': 223, 'z': 300, 'p': 908}
sum:  1886


In [5]:
#35. Python program to find the size of a dictionary
import sys
dic1 = {"A": 1, "B": 2, "C": 3}
dic2 = {"mannu": "Raju", "bala": "Nikhil", "vijay": "Deepanshu"}
dic3 = {1: "Lion", 2: "Tiger", 3: "Fox", 4: "Wolf"}
print("Size of dic1: " + str(sys.getsizeof(dic1)) + "bytes")
print("Size of dic2: " + str(sys.getsizeof(dic2)) + "bytes")
print("Size of dic3: " + str(sys.getsizeof(dic3)) + "bytes")

Size of dic1: 232bytes
Size of dic2: 232bytes
Size of dic3: 232bytes


In [7]:
#36. Find the size of a set in Python
import sys
Set1 = {"A", 1, "B", 2, "C", 3}
Set2 = {"mannu", "Raju", "bala", "Nikhil", "vijay", "Deepanshu"}
Set3 = {(1, "Lion"), ( 2, "Tiger"), (3, "Fox")}
print("Size of Set1: " + str(sys.getsizeof(Set1)) + "bytes")
print("Size of Set2: " + str(sys.getsizeof(Set2)) + "bytes")
print("Size of Set3: " + str(sys.getsizeof(Set3)) + "bytes")

Size of Set1: 472bytes
Size of Set2: 472bytes
Size of Set3: 216bytes


In [1]:
#37. Iterate over a set in Python

test_set = set("yorichi")
 

for val in test_set:
    print(val)

y
o
h
i
c
r


In [3]:
#38. Python- Maximum and minimum in a Set
sets=set([23,8,19,28,25,78,98,345,678,999])
print("The maximum element in the set is:",max(sets))
print("The minimum element in the set is:",min(sets))

The maximum element in the set is: 999
The minimum element in the set is: 8


In [9]:
#39. Python-Remove items from a set
languages={'Python','Java','English','C','C++','Tamil','Hindi'}
languages.remove('C')
print(languages)

{'English', 'Java', 'Tamil', 'C++', 'Hindi', 'Python'}


In [4]:
#40. Python-Check if two lists have atleast one element in common
def common(list1,list2):
    result=False
    for x in list1:
        for y in list2:
            if x==y:
                result=True
                return result
    return result
a=[1,2,3,4,5]
b=[5,6,7,8,9]
print(common(a,b))
a=[1,2,3,4,5]
b=[6,7,8,9]
print(common(a,b))

True
False


In [8]:
#41. Python-Assigning subsequent rows to matrix first row elements
test_list=[[5,8,9],[2,0,9],[5,4,2],[2,3,9]]
print("The original list:"+str(test_list))
print(test_list[0])
res={test_list[0][ele]:test_list[ele+1] for ele in range(len(test_list)-1)}
print("The assigned matrix:" +str(res))

The original list:[[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]
[5, 8, 9]
The assigned matrix:{5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


In [2]:
#42. Adding and Subtracting matrices in python
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[4,5],[6,7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A,B))
print("Subtraction of two matrix")
print(np.subtract(A,B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


In [14]:
#43. Python-Group similar elements into Matrix
from itertools import groupby
test_list=[1,3,5,1,3,2,5,4,2]
print("The original list:" +str(test_list))
res =[list(val) for key, val in groupby(sorted(test_list))]
print("Matrix after grouping:"+str(res))

The original list:[1, 3, 5, 1, 3, 2, 5, 4, 2]
Matrix after grouping:[[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [15]:
#45)Create an n x n square matrix, where all the sub-matrix has the sum of opposite corner elements as even
import itertools


def sub_mat_even(n):
    
    temp = itertools.count(1)
    l = [[next(temp)for i in range(n)]for i in range(n)]
    if n%2 == 0:
        for i in range(0,len(l)):
            if i%2 == 1:
                l[i][:] = l[i][::-1]
    for i in range(n):
        for j in range(n):
            print(l[i][j],end=" ")
        print()
n = 4
sub_mat_even(n)

1 2 3 4 
8 7 6 5 
9 10 11 12 
16 15 14 13 


In [16]:
#46)How to get list of parameters name from a function in Python?

def fun(a, b):
    return a**b
import inspect
print(inspect.signature(fun))

(a, b)


In [18]:
#47)How to Print Multiple Arguments in Python?
def pri(name, num="25"):
    print("Hello from", name + ', ' + num)


pri("gfg")
pri("gfg", "26")

Hello from gfg, 25
Hello from gfg, 26


In [25]:
#48)Python program to find the power of a number using recursion
def power(N, P):


    if P == 0:
        return 1

    return (N*power(N, P-1))


if __name__ == '__main__':
    a = 5
    b = 2

print(power(a, b))

25


In [26]:
#49)Sorting objects of user defined class in Python

class vickey():
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __repr__(self):
        return str((self.a, self.b))


# list of objects
a=[vickey("venna", 1),
    vickey("computer", 3),
    vickey("for", 2),
    vickey("vickey", 4),
    vickey("hello", 3)]


print(sorted(a, key=lambda x: x.b))

[('venna', 1), ('for', 2), ('computer', 3), ('hello', 3), ('vickey', 4)]


In [17]:
#50)Functions that accept variable length key value pair as arguments


def printKwargs(**kwargs):
    print(kwargs)


# driver code
if __name__ == "__main__":
    printKwargs(Argument_1='vickey', Argument_2='vijay')

{'Argument_1': 'vickey', 'Argument_2': 'vijay'}
